### PR TITLE
Add arch aur package

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
I've added a AUR package for haste-applet too. Still having an issue with a missing `PeasGtk` even if i've added the `libpeas` as a depend. I will see what i can do soon

Update : works fine with `budgie-desktop-git` too.

### CODE REVIEW

**Comment by cybre** [comment]
The licence is GPL2 (not GPL3)

**Comment by bilelmoussaoui** [comment]
Fixed

**Comment by bilelmoussaoui** [comment]
@cybre Can you take a look at this ? :)the same for the screenshot-applet

**Comment by cybre** [comment]
Looks good to me. Does it actually work?

**Comment by cybre** [comment]
I'm going to do a 0.2.2 probably tonight. I'll notify you when it's out and I'll merge this PR once you update the AUR package.

**Comment by cybre** [comment]
I'm also going to release screenshot-applet 3.0 (or 0.2.2) so It's the same for that

**Comment by bilelmoussaoui** [comment]
Yes it works pertectly. Alright :)

**Comment by cybre** [comment]
You can now update the AUR package. The current version is 0.2.3. screenshot-applet will be ready as soon as @alpha is done with the icons.

**Comment by cybre** [comment]
Please update the packages :)

**Comment by bilelmoussaoui** [comment]
Done :)

**Pull request merged**
